export const dataQuestion = {
  status: true,
  total: 187099,
  data: [
    {
      _id: "639056ca02da91dcc515afe1",
      _companyShareIdKey: 1,
      name: null,
      text: ' Are there beaches in Los Angeles?<a id="_heading=h.nhmqo5io5wb6"></a>',
      text_latex:
        ' Are there beaches in Los Angeles?<a id="_heading=h.nhmqo5io5wb6"></a>',
      isMathFormula: false,
      quiz_type: 4,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution: null,
      listClass: [
        {
          name: "Lớp 1",
          idClass: 1,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Việt",
          idSubject: 2,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: {
        listKeyword: [
          'Yes, there are.<a id="_heading=h.x2qxfgx1zg2y"></a><a id="_heading=h.1ehrkjj3dou3"></a><a id="_heading=h.t33qxy6uki00"></a>',
        ],
        isExact: false,
        isCapital: false,
      },
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T09:03:06.877Z",
      updatedAt: "2022-12-07T10:04:57.690Z",
      idQuestion: 1,
      properties: {},
      updatedBy: "superAdmin@hocmai.vn",
      image: null,
      audio: "",
      video: "",
      solution_image: null,
      listSelectOptions: [],
      listQuestionChildren: [],
    },
    {
      _id: "639056ca02da91dcc515afd6",
      _companyShareIdKey: 1,
      name: null,
      text: 'What’s the weather like in Los Angeles?<a id="_heading=h.m51dg7pio3mf"></a>',
      text_latex:
        'What’s the weather like in Los Angeles?<a id="_heading=h.m51dg7pio3mf"></a>',
      isMathFormula: false,
      quiz_type: 4,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution: null,
      listClass: [
        {
          name: "Lớp 1",
          idClass: 1,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Việt",
          idSubject: 2,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: {
        listKeyword: [
          "It’s always sunny",
          "always sunny",
          'sunny<a id="_heading=h.dywcv4yhwkf"></a>',
        ],
        isExact: false,
        isCapital: false,
      },
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T09:03:06.735Z",
      updatedAt: "2022-12-07T09:03:06.735Z",
      idQuestion: 2,
      image: null,
      audio: null,
      video: null,
      solution_image: null,
      listSelectOptions: [],
      listQuestionChildren: [],
    },
    {
      _id: "639056ca02da91dcc515afcb",
      _companyShareIdKey: 1,
      name: null,
      text: ' Where is Hollywood?<a id="_heading=h.6g71d7j2vzkk"></a>',
      text_latex: ' Where is Hollywood?<a id="_heading=h.6g71d7j2vzkk"></a>',
      isMathFormula: false,
      quiz_type: 4,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution: null,
      listClass: [
        {
          name: "Lớp 1",
          idClass: 1,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Việt",
          idSubject: 2,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: {
        listKeyword: [
          "Hollywood is in Los Angeles",
          "Los Angeles",
          'in Los Angeles<a id="_heading=h.bmeua13e4zkp"></a>',
        ],
        isExact: false,
        isCapital: false,
      },
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T09:03:06.580Z",
      updatedAt: "2022-12-07T09:03:06.580Z",
      idQuestion: 3,
      image: null,
      audio: null,
      video: null,
      solution_image: null,
      listSelectOptions: [],
      listQuestionChildren: [],
    },
    {
      _id: "639056ca02da91dcc515afbc",
      _companyShareIdKey: 1,
      name: null,
      text: 'Chi tiết “<em>thấy mắt A Phủ trừng trừng</em>” đã diễn tả tâm trạng tức giận của A Phủ đúng hay sai? <a id="_heading=h.j4tq5q25ja3t"></a>',
      text_latex:
        'Chi tiết “<em>thấy mắt A Phủ trừng trừng</em>” đã diễn tả tâm trạng tức giận của A Phủ đúng hay sai? <a id="_heading=h.j4tq5q25ja3t"></a>',
      isMathFormula: false,
      quiz_type: 3,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution: null,
      listClass: [
        {
          name: "Lớp 1",
          idClass: 1,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Việt",
          idSubject: 2,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: null,
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T09:03:06.457Z",
      updatedAt: "2022-12-07T09:03:06.457Z",
      idQuestion: 4,
      image: null,
      audio: null,
      video: null,
      solution_image: null,
      listSelectOptions: [
        {
          answer_content: 'Đúng<a id="_heading=h.yd3p2rc6bk3m"></a>',
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: true,
          answer_id: 672478,
        },
        {
          answer_content:
            'Sai<a id="_heading=h.5nmq5mk65qi4"></a><a id="_heading=h.xm8ays6fa133"></a><a id="_heading=h.f3ydy6vjfqll"></a>',
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672479,
        },
      ],
      listQuestionChildren: [],
    },
    {
      _id: "639056ca02da91dcc515afa9",
      _companyShareIdKey: 1,
      name: null,
      text: "Các từ nào sau đây có thể thay thế cho từ “<em>gà gáy sáng</em>” (gạch chân, in đậm) trong văn bản trên",
      text_latex:
        "Các từ nào sau đây có thể thay thế cho từ “<em>gà gáy sáng</em>” (gạch chân, in đậm) trong văn bản trên",
      isMathFormula: false,
      quiz_type: 2,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution:
        "Các từ có thể thay thế được là từ đồng nghĩa. Ở đây từ đồng nghĩa với từ “gà gáy sáng” là các từ “tờ mờ sáng”, “ mặt trời lên”",
      listClass: [
        {
          name: "Lớp 1",
          idClass: 1,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Việt",
          idSubject: 2,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: null,
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T09:03:06.322Z",
      updatedAt: "2022-12-07T09:03:06.322Z",
      idQuestion: 5,
      image: null,
      audio: null,
      video: null,
      solution_image: null,
      listSelectOptions: [
        {
          answer_content: "Tờ mờ sáng.",
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: true,
          answer_id: 672474,
        },
        {
          answer_content: "Trời chưa sáng.",
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672475,
        },
        {
          answer_content: "Mặt trời lên.",
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: true,
          answer_id: 672476,
        },
        {
          answer_content: 'Đêm vừa xuống.<a id="_heading=h.jorm9dlppjjr"></a>',
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672477,
        },
      ],
      listQuestionChildren: [],
    },
    {
      _id: "639056ca02da91dcc515af96",
      _companyShareIdKey: 1,
      name: null,
      text: "Từ “<em>dóm lò</em>” (gạch chân, in đậm) trong văn bản dùng để chỉ hành động nào sau đây?",
      text_latex:
        "Từ “<em>dóm lò</em>” (gạch chân, in đậm) trong văn bản dùng để chỉ hành động nào sau đây?",
      isMathFormula: false,
      quiz_type: 1,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution:
        'Qua diễn biến tâm lí của nhân vật Mị, nhà văn Tô Hoài muốn khẳng định: bạo lực không thể đè bẹp, hủy diệt khát vọng sống, khát vọng tự do, hạnh phúc. Chỉ có điều là để có được sự sống, tự do, hạnh phúc, con người đã phải trải qua nhiều tủi nhục, đắng cay.<a id="_heading=h.ze3irwqst9gx"></a>',
      listClass: [
        {
          name: "Lớp 1",
          idClass: 1,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Việt",
          idSubject: 2,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: null,
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T09:03:06.181Z",
      updatedAt: "2022-12-07T09:03:06.181Z",
      idQuestion: 6,
      image: null,
      audio: null,
      video: null,
      solution_image: null,
      listSelectOptions: [
        {
          answer_content: "Làm cho ngọn lửa bắt vào củi trong bếp để đun nấu.",
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672470,
        },
        {
          answer_content: "Dựng một cái bếp bằng củi để nấu ăn ở ngoài trời.",
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672471,
        },
        {
          answer_content: "Dùng củi và bùn tạo thành than để đun nấu.",
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: true,
          answer_id: 672472,
        },
        {
          answer_content:
            'Sử dụng gạch và vôi để dựng bếp đun nấu trong gia đình. <a id="_heading=h.ne60ygm3obaz"></a>',
          answer_content_latex: null,
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672473,
        },
      ],
      listQuestionChildren: [],
    },
    {
      _id: "639056c902da91dcc515af8a",
      _companyShareIdKey: 1,
      name: null,
      text: "Văn bản trên đã sử dụng phương thức biểu đạt chính nào?",
      text_latex: "Văn bản trên đã sử dụng phương thức biểu đạt chính nào?",
      isMathFormula: false,
      quiz_type: 4,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution:
        " Xác định phương thức biểu đạt chính của văn bản là xác định cách cốt yếu mà người viết truyền tải những thông tin, thông điệp đến với người khác. Qua đó thể hiện, bày tỏ những tình cảm, tâm tư và suy nghĩ của chính mình với những đối tượng đang đọc tác phẩm đó. Ở đây tác giả đang kể một câu chuyện và sử dụng phương thức tự sự.",
      listClass: [
        {
          name: "Lớp 1",
          idClass: 1,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Việt",
          idSubject: 2,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: {
        listKeyword: ['Tự sự<a id="_heading=h.qanqfptxt49e"></a>'],
        isExact: false,
        isCapital: false,
      },
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T09:03:05.970Z",
      updatedAt: "2022-12-07T09:03:05.970Z",
      idQuestion: 7,
      image: null,
      audio: null,
      video: null,
      solution_image: null,
      listSelectOptions: [],
      listQuestionChildren: [],
    },
    {
      _id: "63905597e840edc19ecc5278",
      _companyShareIdKey: 1,
      name: null,
      text: 'Dao động của một vật là tổng hợp của hai dao động điều hòa cùng phương, có phương trình lần lượt là. <sub><math><msub><mi mathvariant="normal">x</mi><mn>1</mn></msub><mo>=</mo><msub><mi mathvariant="normal">A</mi><mn>1</mn></msub><mi>cos</mi><mfenced close=")" open="(" separators=""><mn>10</mn><mi mathvariant="normal">t</mi><mo>+</mo><mfrac><mi mathvariant="normal">π</mi><mn>6</mn></mfrac></mfenced><mspace width="0.08em"/><mi>cm</mi></math></sub> và <sub><math><msub><mi mathvariant="normal">x</mi><mn>2</mn></msub><mo>=</mo><mn>10</mn><mi>cos</mi><mfenced close=")" open="(" separators=""><mn>10</mn><mi mathvariant="normal">t</mi><mo>+</mo><mfrac><mrow><mn>2</mn><mi mathvariant="normal">π</mi></mrow><mn>3</mn></mfrac></mfenced><mspace width="0.08em"/><mi>cm</mi><mo>.</mo></math></sub> Biết rằng tốc độ cực đại của vật bằng <sub><math><mn>100</mn><msqrt><mn>2</mn></msqrt><mspace width="0.08em"/><mi>cm</mi><mo>/</mo><mi mathvariant="normal">s</mi><mo>.</mo></math></sub> Biên độ A<sub>1</sub> có giá trị là',
      text_latex:
        "Dao động của một vật là tổng hợp của hai dao động điều hòa cùng phương, có phương trình lần lượt là. <sub>$x_{1}=A_{1}cos\\left(10,t,+,\\frac{\\pi}{6}\\right)cm$</sub> và <sub>$x_{2}=10cos\\left(10,t,+,\\frac{2 \\pi}{3}\\right)cm.$</sub> Biết rằng tốc độ cực đại của vật bằng <sub>$100\\sqrt{2}cm/s.$</sub> Biên độ A<sub>1</sub> có giá trị là",
      isMathFormula: true,
      quiz_type: 1,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution:
        '<sub><math><msub><mi mathvariant="normal">v</mi><mi>max</mi></msub><mo>=</mo><mi>ωA</mi><mo>=</mo><mn>100</mn><msqrt><mn>2</mn></msqrt><mspace width="0.08em"/><mi>cm</mi><mo>/</mo><mi mathvariant="normal">s</mi><mo>→</mo><mi mathvariant="normal">A</mi><mo>.</mo><mn>10</mn><mo>=</mo><mn>100</mn><msqrt><mn>2</mn></msqrt><mo>→</mo><mi mathvariant="normal">A</mi><mo>=</mo><mn>10</mn><msqrt><mn>2</mn></msqrt><mspace width="0.08em"/><mi>cm</mi></math></sub> <sub><math><mtable columnalign="left"><mtr><mtd><msup><mi mathvariant="normal">A</mi><mn>2</mn></msup><mo>=</mo><msubsup><mi mathvariant="normal">A</mi><mn>1</mn><mn>2</mn></msubsup><mo>+</mo><msubsup><mi mathvariant="normal">A</mi><mn>2</mn><mn>2</mn></msubsup><mo>+</mo><mn>2</mn><msub><mi mathvariant="normal">A</mi><mn>1</mn></msub><msub><mi mathvariant="normal">A</mi><mn>2</mn></msub><mtext>cos</mtext><mfenced close=")" open="(" separators=""><msub><mi mathvariant="normal">φ</mi><mn>2</mn></msub><mo>−</mo><msub><mi mathvariant="normal">φ</mi><mn>1</mn></msub></mfenced><mo>→</mo><msup><mfenced close=")" open="(" separators=""><mn>10</mn><msqrt><mn>2</mn></msqrt></mfenced><mn>2</mn></msup><mo>=</mo><msubsup><mi mathvariant="normal">A</mi><mn>1</mn><mn>2</mn></msubsup><mo>+</mo><msup><mn>10</mn><mn>2</mn></msup><mo>+</mo><mn>2</mn><msub><mi mathvariant="normal">A</mi><mn>1</mn></msub><mo>.</mo><mn>10</mn><mo>.</mo><mtext>cos</mtext><mfenced close=")" open="(" separators=""><mfrac><mi mathvariant="normal">π</mi><mn>6</mn></mfrac><mo>−</mo><mfrac><mrow><mn>2</mn><mi mathvariant="normal">π</mi></mrow><mn>3</mn></mfrac></mfenced></mtd></mtr><mtr><mtd><mo>→</mo><msub><mi mathvariant="normal">A</mi><mn>1</mn></msub><mo>=</mo><mn>10</mn><mspace width="0.08em"/><mi>cm</mi><mo>.</mo></mtd></mtr></mtable></math></sub><img src="https://apiemsdev.hocmai.net/resource/uploads/image/e1bd9b2e-9976-4ecb-8d0b-5cb11c7a1de2.emf.svg" />Gọi <math><mi>H</mi></math> là trung điểm <math><mi>B</mi><mi>C</mi></math><math><mo>⇒</mo><mi>A</mi><mi>H</mi><mo>⊥</mo><mi>B</mi><mi>C</mi></math>.Ta có: <math><mfenced close="}" open="" separators=""><mtable columnalign="left"><mtr><mtd><mi>A</mi><msup><mi>A</mi><mo>′</mo></msup><mo>⊥</mo><mfenced close=")" open="(" separators=""><mi>A</mi><mi>B</mi><mi>C</mi></mfenced></mtd></mtr><mtr><mtd><mi>B</mi><mi>C</mi><mo>⊂</mo><mfenced close=")" open="(" separators=""><mi>A</mi><mi>B</mi><mi>C</mi></mfenced></mtd></mtr></mtable></mfenced></math><math><mo>⇒</mo><mi>B</mi><mi>C</mi><mo>⊥</mo><mi>A</mi><msup><mi>A</mi><mo>′</mo></msup></math><math><mo>⇒</mo></math> Góc giữa <math><mfenced close=")" open="(" separators=""><msup><mi>A</mi><mo>′</mo></msup><mi>B</mi><mi>C</mi></mfenced></math>và <math><mfenced close=")" open="(" separators=""><mi>A</mi><mi>B</mi><mi>C</mi></mfenced></math> là <math><mn>30</mn><mo>°</mo></math>.Gọi <math><mi>B</mi><mi>C</mi><mo>=</mo><mn>2</mn><mi>x</mi></math>, theo bài ra ta có:<math><mfenced close="" open="{" separators=""><mtable columnalign="left"><mtr><mtd><mi>A</mi><mi>H</mi><mo>=</mo><mi>x</mi><msqrt><mn>3</mn></msqrt></mtd></mtr><mtr><mtd><mi>A</mi><msup><mi>A</mi><mo>′</mo></msup><mo>=</mo><mi>A</mi><mi>H</mi><mo>.</mo><mi>tan30</mi><mo>°</mo><mo>=</mo><mi>x</mi></mtd></mtr></mtable></mfenced></math> <math><mo>⇒</mo><msup><mi>A</mi><mo>′</mo></msup><mi>H</mi><mo>=</mo><msqrt><mi>A</mi><msup><msup><mi>A</mi><mo>′</mo></msup><mn>2</mn></msup><mo>+</mo><mi>A</mi><msup><mi>H</mi><mn>2</mn></msup></msqrt><mo>=</mo><mn>2</mn><mi>x</mi></math>.Mà <math><msub><mi>S</mi><mrow><mi mathvariant="normal">Δ</mi><msup><mi>A</mi><mo>′</mo></msup><mi>B</mi><mi>C</mi></mrow></msub><mo>=</mo><mn>4</mn><msup><mi>a</mi><mn>2</mn></msup></math><math><mo>⇔</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mi>B</mi><mi>C</mi><mo>.</mo><msup><mi>A</mi><mo>′</mo></msup><mi>H</mi><mo>=</mo><mn>4</mn><msup><mi>a</mi><mn>2</mn></msup></math><math><mo>⇔</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mo>.</mo><mn>2</mn><mi>x</mi><mo>.</mo><mn>2</mn><mi>x</mi><mo>=</mo><mn>4</mn><msup><mi>a</mi><mn>2</mn></msup></math><math><mo>⇒</mo><mi>x</mi><mo>=</mo><mi>a</mi><msqrt><mn>2</mn></msqrt></math>.Vậy thể tích cần tìm là <math><mi>V</mi><mo>=</mo><msub><mi>S</mi><mrow><mi mathvariant="normal">Δ</mi><mi>A</mi><mi>B</mi><mi>C</mi></mrow></msub><mo>.</mo><mi>A</mi><msup><mi>A</mi><mo>′</mo></msup></math><math><mo>=</mo><mfenced close=")" open="(" separators=""><msup><mfenced close=")" open="(" separators=""><mn>2</mn><mi>a</mi><msqrt><mn>2</mn></msqrt></mfenced><mn>2</mn></msup><mo>.</mo><mfrac><msqrt><mn>3</mn></msqrt><mn>4</mn></mfrac></mfenced><mo>.</mo><mi>a</mi><msqrt><mn>2</mn></msqrt><mo>=</mo><mn>2</mn><msup><mi>a</mi><mn>3</mn></msup><msqrt><mn>6</mn></msqrt></math>.',
      listClass: [
        {
          name: "Lớp 12",
          idClass: 12,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Anh",
          idSubject: 3,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: null,
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T08:57:59.945Z",
      updatedAt: "2022-12-07T08:57:59.945Z",
      idQuestion: 8,
      image: null,
      audio: null,
      video: null,
      solution_image: null,
      listSelectOptions: [
        {
          answer_content:
            '<sub><math><mn>8</mn><msqrt><mn>2</mn></msqrt><mspace width="0.08em"/><mi>cm</mi><mo>.</mo></math></sub>',
          answer_content_latex: "<sub>$8\\sqrt{2}cm.$</sub>",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672466,
        },
        {
          answer_content:
            '<sub><math><mn>6</mn><msqrt><mn>2</mn></msqrt><mspace width="0.08em"/><mi>cm</mi><mo>.</mo></math></sub>',
          answer_content_latex: "<sub>$6\\sqrt{2}cm.$</sub>",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672467,
        },
        {
          answer_content: "10 cm.",
          answer_content_latex: "10 cm.",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: true,
          answer_id: 672468,
        },
        {
          answer_content:
            '<sub><math><mn>10</mn><msqrt><mn>2</mn></msqrt><mspace width="0.08em"/><mi>cm</mi><mo>.</mo></math></sub>',
          answer_content_latex: "<sub>$10\\sqrt{2}cm.$</sub>",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672469,
        },
      ],
      listQuestionChildren: [],
    },
    {
      _id: "63905597e840edc19ecc5265",
      _companyShareIdKey: 1,
      name: null,
      text: 'Cho khối trụ đứng <math><mi>A</mi><mi>B</mi><mi>C</mi><mo>.</mo><msup><mi>A</mi><mo>′</mo></msup><msup><mi>B</mi><mo>′</mo></msup><msup><mi>C</mi><mo>′</mo></msup></math> có đáy là tam giác đều. Mặt phẳng <math><mfenced close=")" open="(" separators=""><msup><mi>A</mi><mo>′</mo></msup><mi>B</mi><mi>C</mi></mfenced></math> tạo với đáy một góc <math><mn>30</mn><mo>°</mo></math> và tam giác <math><msup><mi>A</mi><mo>′</mo></msup><mi>B</mi><mi>C</mi></math> có diện tích bằng <math><mn>4</mn><msup><mi>a</mi><mn>2</mn></msup></math>. Tính thể tích <math><mi>V</mi></math> của khối lăng trụ đã cho.',
      text_latex:
        "Cho khối trụ đứng $ABC.A^{'}B^{'}C^{'}$ có đáy là tam giác đều. Mặt phẳng $\\left(A^{'},B,C\\right)$ tạo với đáy một góc $30\\circ$ và tam giác $A^{'}BC$ có diện tích bằng $4a^{2}$. Tính thể tích $V$ của khối lăng trụ đã cho.",
      isMathFormula: true,
      quiz_type: 1,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution: null,
      listClass: [
        {
          name: "Lớp 12",
          idClass: 12,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Anh",
          idSubject: 3,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: null,
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T08:57:59.762Z",
      updatedAt: "2022-12-07T08:57:59.762Z",
      idQuestion: 9,
      image: null,
      audio: null,
      video: null,
      solution_image: null,
      listSelectOptions: [
        {
          answer_content:
            "<math><mi>V</mi><mo>=</mo><mn>8</mn><msup><mi>a</mi><mn>3</mn></msup><msqrt><mn>6</mn></msqrt></math>.",
          answer_content_latex: "$V=8a^{3}\\sqrt{6}$.",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672462,
        },
        {
          answer_content:
            "<math><mi>V</mi><mo>=</mo><mn>2</mn><msup><mi>a</mi><mn>3</mn></msup><msqrt><mn>6</mn></msqrt></math>.",
          answer_content_latex: "$V=2a^{3}\\sqrt{6}$.",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: true,
          answer_id: 672463,
        },
        {
          answer_content:
            "<math><mi>V</mi><mo>=</mo><mn>8</mn><msup><mi>a</mi><mn>3</mn></msup><msqrt><mn>3</mn></msqrt></math>.",
          answer_content_latex: "$V=8a^{3}\\sqrt{3}$.",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672465,
        },
        {
          answer_content:
            "<math><mi>V</mi><mo>=</mo><mn>16</mn><msup><mi>a</mi><mn>3</mn></msup><msqrt><mn>3</mn></msqrt></math>.",
          answer_content_latex: "$V=16a^{3}\\sqrt{3}$.",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672464,
        },
      ],
      listQuestionChildren: [],
    },
    {
      _id: "63905597e840edc19ecc5252",
      _companyShareIdKey: 1,
      name: null,
      text: 'Cho hình chóp <em>S.ABC</em> có <em>SA</em> vuông góc với mặt phẳng <math><mfenced close=")" open="(" separators=""><mi>A</mi><mi>B</mi><mi>C</mi></mfenced><mn>,</mn></math><math><mi>S</mi><mi>A</mi><mo>=</mo><mn>2</mn><mi>a</mi><mn>,</mn></math> tam giác <em>ABC</em> vuông tại <em>B</em>, <math><mi>A</mi><mi>B</mi><mo>=</mo><mi>a</mi><msqrt><mn>3</mn></msqrt></math> và <math><mi>B</mi><mi>C</mi><mo>=</mo><mi>a</mi></math>(minh họa như hình vẽ bên). Góc giữa đường thẳng <em>SC</em> và mặt phẳng <math><mfenced close=")" open="(" separators=""><mi>A</mi><mi>B</mi><mi>C</mi></mfenced></math> bằng<img src="https://apiemsdev.hocmai.net/resource/uploads/image/1dbdbc76-df81-408f-95a3-8413c84dbea5.emf.svg" />',
      text_latex:
        'Cho hình chóp <em>S.ABC</em> có <em>SA</em> vuông góc với mặt phẳng $\\left(A,B,C\\right),$$SA=2a,$ tam giác <em>ABC</em> vuông tại <em>B</em>, $AB=a\\sqrt{3}$ và $BC=a$(minh họa như hình vẽ bên). Góc giữa đường thẳng <em>SC</em> và mặt phẳng $\\left(A,B,C\\right)$ bằng<img src="https://apiemsdev.hocmai.net/resource/uploads/image/1dbdbc76-df81-408f-95a3-8413c84dbea5.emf.svg" />',
      isMathFormula: true,
      quiz_type: 1,
      level: 1,
      type: 0,
      awareness_level: 1,
      answer_type: 0,
      solution:
        'Ta có <math><mi>S</mi><mi>A</mi><mo>⊥</mo><mfenced close=")" open="(" separators=""><mi>A</mi><mi>B</mi><mi>C</mi></mfenced></math> nên <em>AC</em> là hình chiếu của <em>SC</em> lên mặt phẳng <math><mfenced close=")" open="(" separators=""><mi>A</mi><mi>B</mi><mi>C</mi></mfenced><mo>.</mo></math> Do đó <math><mfenced close=")" open="(" separators=""><mi>S</mi><mi>C</mi><mn>,</mn><mfenced close=")" open="(" separators=""><mi>A</mi><mi>B</mi><mi>C</mi></mfenced></mfenced><mo>=</mo><mfenced close=")" open="(" separators=""><mi>S</mi><mi>C</mi><mn>,</mn><mi>A</mi><mi>C</mi></mfenced><mo>=</mo><mover accent="true"><mrow><mi>S</mi><mi>C</mi><mi>A</mi></mrow><mo stretchy="true">^</mo></mover><mo>.</mo></math> Tam giác <em>ABC</em> vuông tại <em>B</em> có <math><mi>A</mi><mi>B</mi><mo>=</mo><mi>a</mi><msqrt><mn>3</mn></msqrt></math> và <math><mi>B</mi><mi>C</mi><mo>=</mo><mi>a</mi></math> nên <math><mi>A</mi><mi>C</mi><mo>=</mo><msqrt><mi>A</mi><msup><mi>B</mi><mn>2</mn></msup><mo>+</mo><mi>B</mi><msup><mi>C</mi><mn>2</mn></msup></msqrt><mo>=</mo><msqrt><mn>4</mn><msup><mi>a</mi><mn>2</mn></msup></msqrt><mo>=</mo><mn>2</mn><mi>a</mi><mo>.</mo></math> Do đó tam giác <em>SAC</em> vuông cân tại <em>A</em> nên <math><mover accent="true"><mrow><mi>S</mi><mi>C</mi><mi>A</mi></mrow><mo stretchy="true">^</mo></mover><mo>=</mo><mn>45</mn><mo>°</mo><mo>.</mo></math> Vậy <math><mfenced close=")" open="(" separators=""><mi>S</mi><mi>C</mi><mn>,</mn><mfenced close=")" open="(" separators=""><mi>A</mi><mi>B</mi><mi>C</mi></mfenced></mfenced><mo>=</mo><mn>45</mn><mo>°</mo><mo>.</mo></math>',
      listClass: [
        {
          name: "Lớp 12",
          idClass: 12,
        },
      ],
      listSubject: [
        {
          name: "Tiếng Anh",
          idSubject: 3,
        },
      ],
      listKnowledgeUnit: [],
      listTag: [],
      count: 0,
      count_turns_correct: 0,
      listShortAnswer: null,
      listPairOptions: {
        keys: null,
        values: null,
      },
      listSortOptions: null,
      speakElsa: null,
      createdBy: "superAdmin@hocmai.vn",
      createdAt: "2022-12-07T08:57:59.593Z",
      updatedAt: "2022-12-07T08:57:59.593Z",
      idQuestion: 10,
      image: null,
      audio: null,
      video: null,
      solution_image: null,
      listSelectOptions: [
        {
          answer_content: "<math><mn>90</mn><mo>°</mo><mo>.</mo></math>",
          answer_content_latex: "$90\\circ.$",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672458,
        },
        {
          answer_content: "<math><mn>45</mn><mo>°</mo><mo>.</mo></math>",
          answer_content_latex: "$45\\circ.$",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: true,
          answer_id: 672459,
        },
        {
          answer_content: "<math><mn>30</mn><mo>°</mo><mo>.</mo></math>",
          answer_content_latex: "$30\\circ.$",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672460,
        },
        {
          answer_content: "<math><mn>60</mn><mo>°</mo><mo>.</mo></math>",
          answer_content_latex: "$60\\circ.$",
          answer_url_image: null,
          answer_url_mp3: null,
          is_true: false,
          answer_id: 672461,
        },
      ],
      listQuestionChildren: [],
    },
  ],
};
